apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backfill-cron-workflow.yaml
  - images.yaml
  - obslytics-cron-workflow.yaml
  - triggers.yaml
  - verification-cron-workflow.yaml
  - workflow-templates.yaml
  - alert-template.yaml
  - dataviz.yaml
